import React, { useEffect, useState } from "react";
import ReactDOM from "react-dom/client";
import { BrowserRouter, Routes, Route, Outlet } from "react-router-dom";
import { ThemeLayout } from "../theme/Layout";
import { NotFound } from "../theme/NotFound";
import { Loading } from "../theme/Loading";
import { Navbar } from "../theme/Navbar";
import { CodeBlock } from "../theme/CodeBlock";
import { Video } from "../theme/Video";
import { MDXProvider } from "@mdx-js/react";
import { createContext, useContext } from "react";

export const ConfigContext = createContext<any>(null);

export function useConfig() {
  return useContext(ConfigContext);
}

import { PackageManagerTabs } from "../theme/PackageManagerTabs";
import "../theme/pkg-tabs.css";
declare global {
  interface ImportMeta {
    env: Record<string, any>;
  }
}

import { PreloadProvider } from "./preload";

/** MDX component overrides – maps <pre> to our CodeBlock */
const mdxComponents = {
  pre: (props: any) => <CodeBlock {...props}>{props.children}</CodeBlock>,
  video: (props: any) => <Video {...props} />,
  PackageManagerTabs,
};

/**
 * Metadata provided by the server for a specific route.
 * Maps closely to the `RouteMeta` type in the Node environment.
 */
export interface ComponentRoute {
  /** The final URL path */
  path: string;
  /** The absolute filesystem path of the source file */
  componentPath: string;
  /** The page title */
  title: string;
  /** Explicit order in the sidebar */
  sidebarPosition?: number;
  /** The relative path from the docs directory */
  filePath: string;
  /** The group directory name */
  group?: string;
  /** The display title of the group */
  groupTitle?: string;
  /** Explicit order of the group in the sidebar */
  groupPosition?: number;
  /** Extracted markdown headings for search indexing */
  headings?: { level: number; text: string; id: string }[];
  /** The locale this route belongs to, if i18n is configured */
  locale?: string;
}

/**
 * Configuration options for initializing the Litedocs client app.
 */
export interface CreateLitedocsAppOptions {
  /** CSS selector for the DOM element where the app should mount (e.g. '#root') */
  target: string;
  /** Initial routes generated by the Vite plugin (`virtual:litedocs-routes`) */
  routes: ComponentRoute[];
  /** Site configuration (`virtual:litedocs-config`) */
  config: any;
  /** Dynamic import mapping from `import.meta.glob` for the documentation pages */
  modules: Record<string, () => Promise<any>>;
  /** The `import.meta.hot` instance necessary for fast refresh/HMR updates */
  hot?: any;
  /** Optional custom React component to render when visiting the root path ('/') */
  homePage?: React.ComponentType;
}

export function AppShell({
  initialRoutes,
  initialConfig,
  modules,
  hot,
  homePage: HomePage,
}: {
  initialRoutes: ComponentRoute[];
  initialConfig: any;
  modules: Record<string, () => Promise<any>>;
  hot?: any;
  homePage?: React.ComponentType;
}) {
  const [routesInfo, setRoutesInfo] = useState<ComponentRoute[]>(initialRoutes);
  const [config] = useState(initialConfig);
  const [resolvedRoutes, setResolvedRoutes] = useState<any[]>([]);

  // Subscribe to HMR events
  useEffect(() => {
    if (hot) {
      hot.on("litedocs:routes-update", (newRoutes: ComponentRoute[]) => {
        setRoutesInfo(newRoutes);
      });
    }
  }, [hot]);

  // Resolve MDX components
  useEffect(() => {
    const mapped = routesInfo
      .filter(
        (route) => !(HomePage && (route.path === "/" || route.path === "")),
      )
      .map((route) => {
        const loaderKey = Object.keys(modules).find((k) =>
          k.endsWith("/" + route.filePath),
        );
        const loader = loaderKey ? modules[loaderKey] : null;

        return {
          ...route,
          Component: React.lazy(() => {
            if (!loader)
              return Promise.resolve({ default: () => <NotFound /> });
            return loader() as any;
          }),
        };
      });

    setResolvedRoutes(mapped);
  }, [routesInfo, modules]);

  return (
    <ConfigContext.Provider value={config}>
      <PreloadProvider routes={routesInfo} modules={modules}>
        <Routes>
          {/* Custom home page WITHOUT docs layout */}
          {HomePage && (
            <Route
              path="/"
              element={
                <div className="litedocs-layout">
                  <Navbar config={config} routes={routesInfo} />
                  <HomePage />
                </div>
              }
            />
          )}

          {/* Documentation pages WITH sidebar + TOC layout */}
          <Route element={<DocsLayout config={config} routes={routesInfo} />}>
            {resolvedRoutes.map((route: any) => (
              <Route
                key={route.path}
                path={route.path === "" ? "/" : route.path}
                element={
                  <React.Suspense fallback={<Loading />}>
                    <MdxPage Component={route.Component} />
                  </React.Suspense>
                }
              />
            ))}
          </Route>

          <Route
            path="*"
            element={
              <div className="litedocs-layout">
                <Navbar config={config} routes={routesInfo} />
                <NotFound />
              </div>
            }
          />
        </Routes>
      </PreloadProvider>
    </ConfigContext.Provider>
  );
}

/** Wrapper layout for doc pages (sidebar + content + TOC) */
function DocsLayout({
  config,
  routes,
}: {
  config: any;
  routes: ComponentRoute[];
}) {
  return (
    <ThemeLayout config={config} routes={routes}>
      <Outlet />
    </ThemeLayout>
  );
}

/**
 * Renders an MDX page securely, injecting required custom components.
 * For example, this overrides the default `<pre>` HTML tags emitted by MDX
 * with the Litedocs `CodeBlock` component for syntax highlighting.
 *
 * @param props - Contains the dynamically loaded React component representing the MDX page
 */
function MdxPage({ Component }: { Component: React.LazyExoticComponent<any> }) {
  return (
    <MDXProvider components={mdxComponents}>
      <Component />
    </MDXProvider>
  );
}

/**
 * Creates and mounts the Litedocs documentation app.
 *
 * Usage:
 * ```tsx
 * import { createLitedocsApp } from 'litedocs/client'
 * import routes from 'virtual:litedocs-routes'
 * import config from 'virtual:litedocs-config'
 * import 'litedocs/style.css'
 * import HomePage from './HomePage'
 *
 * createLitedocsApp({
 *   target: '#root',
 *   routes,
 *   config,
 *   modules: import.meta.glob('/docs/**\/*.{md,mdx}'),
 *   hot: import.meta.hot,
 *   homePage: HomePage,
 * })
 * ```
 */
export function createLitedocsApp(options: CreateLitedocsAppOptions) {
  const { target, routes, config, modules, hot, homePage } = options;
  const container = document.querySelector(target);
  if (!container) {
    throw new Error(
      `[litedocs] Mount target "${target}" not found in document.`,
    );
  }

  const app = (
    <React.StrictMode>
      <BrowserRouter>
        <AppShell
          initialRoutes={routes}
          initialConfig={config}
          modules={modules}
          hot={hot}
          homePage={homePage}
        />
      </BrowserRouter>
    </React.StrictMode>
  );

  // In production (built app), the HTML is pre-rendered by SSG, so we hydrate.
  // In development, the root is empty, so we createRoot.
  if (import.meta.env.PROD && container.innerHTML.trim() !== "") {
    ReactDOM.hydrateRoot(container as HTMLElement, app);
  } else {
    ReactDOM.createRoot(container as HTMLElement).render(app);
  }
}
