import React from "react";
import ReactDOMServer from "react-dom/server";
import { StaticRouter } from "react-router-dom/server";
import { AppShell, ComponentRoute } from "./app";

/**
 * Options for rendering the Litedocs application on the server (SSG).
 */
export interface RenderOptions {
  /** The URL path currently being rendered */
  path: string;
  /** Initial routes generated by the Vite plugin (`virtual:litedocs-routes`) */
  routes: ComponentRoute[];
  /** Site configuration (`virtual:litedocs-config`) */
  config: any;
  /** Optional custom React component to render when visiting the root path ('/') */
  homePage?: React.ComponentType;
  /** Preloaded modules (since SSR cannot use dynamic imports easily) */
  modules: Record<string, any>;
}

/**
 * Renders the full React application into an HTML string for a specific route.
 * This is called by the Node SSG script during the Vite build process.
 */
export async function render(options: RenderOptions): Promise<string> {
  const { path, routes, config, modules, homePage } = options;

  // For SSR, we must resolve modules synchronously. We create a mock 'loader'
  // that instantly returns the module since the SSG script already loaded it.
  const resolvedModules: Record<string, () => Promise<any>> = {};
  for (const [key, mod] of Object.entries(modules)) {
    resolvedModules[key] = () => Promise.resolve(mod);
  }

  const html = ReactDOMServer.renderToString(
    <React.StrictMode>
      <StaticRouter location={path}>
        <AppShell
          initialRoutes={routes}
          initialConfig={config}
          modules={resolvedModules}
          homePage={homePage}
        />
      </StaticRouter>
    </React.StrictMode>,
  );

  return html;
}
