import React from "react";

/**
 * Metadata provided by the server for a specific route.
 * Maps closely to the `RouteMeta` type in the Node environment.
 */
export interface ComponentRoute {
  /** The final URL path */
  path: string;
  /** The absolute filesystem path of the source file */
  componentPath: string;
  /** The page title */
  title: string;
  /** Explicit order in the sidebar */
  sidebarPosition?: number;
  /** The relative path from the docs directory */
  filePath: string;
  /** The group directory name */
  group?: string;
  /** The display title of the group */
  groupTitle?: string;
  /** Explicit order of the group in the sidebar */
  groupPosition?: number;
  /** Extracted markdown headings for search indexing */
  headings?: { level: number; text: string; id: string }[];
  /** The page summary or description */
  description?: string;
  /** The locale this route belongs to, if i18n is configured */
  locale?: string;
  /** The version this route belongs to, if versioning is configured */
  version?: string;
  /** Optional icon to display (Lucide icon name or raw SVG) */
  icon?: string;
  /** The tab this route belongs to, if tabs are configured */
  tab?: string;
  /** Optional badge to display next to the sidebar item */
  badge?: string | { text: string; expires?: string };
  /** Optional icon for the route's group */
  groupIcon?: string;
  /** The extracted plain-text content of the page for search indexing */
  _content?: string;
  /** The raw markdown content of the page */
  _rawContent?: string;
}

/**
 * Configuration options for initializing the Boltdocs client app.
 */
export interface CreateBoltdocsAppOptions {
  /** CSS selector for the DOM element where the app should mount (e.g. '#root') */
  target: string;
  /** Initial routes generated by the Vite plugin (`virtual:boltdocs-routes`) */
  routes: ComponentRoute[];
  /** The name of the documentation directory (e.g. 'docs') */
  docsDirName: string;
  /** Site configuration (`virtual:boltdocs-config`) */
  config: any;
  /** Dynamic import mapping from `import.meta.glob` for the documentation pages */
  modules: Record<string, () => Promise<any>>;
  /** The `import.meta.hot` instance necessary for fast refresh/HMR updates */
  hot?: any;
  /** Optional custom React component to render when visiting the root path ('/') */
  homePage?: React.ComponentType;
  /** Optional custom MDX components provided by plugins */
  components?: Record<string, React.ComponentType<any>>;
}
